services:
  app1:
    build:
      context: .
    image: myapp-image
    ports:
      - "9080:8080"
    networks:
      - mynet

  app2:
    build:
      context: .
    image: myapp-image
    ports:
      - "9081:8080"
    networks:
      - mynet

  app3:
    build:
      context: .
    image: myapp-image
    ports:
      - "9082:8080"
    networks:
      - mynet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - mynet
      - default

networks:
  mynet:
  default:
